print("Benvenuti al programma \"Moltiplicatore\"")
print("Restituisce in output il risultato di una moltiplicazione tra due numeri!\n")
x = input("Inserisci il primo valore --> ")
y = input("Inserisci il secondo valore --> ")
risultato = float(x) * float(y)
print("Il risultato della moltiplicazione è: ", risultato)
