# Generated by Django 2.1 on 2018-08-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0003_auto_20180810_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='isbn',
            field=models.CharField(max_length=16),
        ),
    ]
