# Generated by Django 2.1 on 2018-08-16 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpostmodel',
            options={'verbose_name': 'blog', 'verbose_name_plural': 'blogs'},
        ),
    ]
