# Generated by Django 2.1 on 2018-08-16 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180816_1226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpostmodel',
            options={},
        ),
    ]
